/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2-mei-2011, 21:36:47
 */

package trafficownage.ui;

import java.text.DecimalFormat;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.UIManager;
import trafficownage.simulation.Car;
import trafficownage.simulation.MainLoop;
import trafficownage.simulation.MainLoopListener;
import trafficownage.simulation.Node;
import trafficownage.simulation.Road;

/**
 *
 * @author Gerrit
 */
public class MainFrame extends javax.swing.JFrame implements MainLoopListener {

    private MainLoop m;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();

        m = new MainLoop();
        m.init(this);

        mapComponent2.init(m);

        mapComponent2.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapComponent1 = new trafficownage.ui.MapComponent();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        timeLabel1 = new javax.swing.JLabel();
        drawModeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        carCountLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mapComponent2 = new trafficownage.ui.MapComponent();
        jPanel3 = new javax.swing.JPanel();
        oldStartButton = new javax.swing.JButton();
        oldPauseButton = new javax.swing.JButton();
        oldStopButton = new javax.swing.JButton();
        increaseSimSpeedButton = new javax.swing.JButton();
        decreaseSimSpeedButton = new javax.swing.JButton();
        simSpeedLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        drawingMenu = new javax.swing.JMenu();
        drawingEnabledCheckbox = new javax.swing.JCheckBoxMenuItem();
        drawCarsRadioButton = new javax.swing.JRadioButtonMenuItem();
        drawDensityRadioButton = new javax.swing.JRadioButtonMenuItem();

        javax.swing.GroupLayout mapComponent1Layout = new javax.swing.GroupLayout(mapComponent1);
        mapComponent1.setLayout(mapComponent1Layout);
        mapComponent1Layout.setHorizontalGroup(
            mapComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mapComponent1Layout.setVerticalGroup(
            mapComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        timeLabel1.setFont(timeLabel1.getFont().deriveFont(timeLabel1.getFont().getStyle() | java.awt.Font.BOLD, timeLabel1.getFont().getSize()+3));
        timeLabel1.setText("     ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roadworx");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        timeLabel.setFont(timeLabel.getFont().deriveFont(timeLabel.getFont().getStyle() | java.awt.Font.BOLD, timeLabel.getFont().getSize()+3));
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("     ");

        carCountLabel.setFont(carCountLabel.getFont().deriveFont(carCountLabel.getFont().getStyle() | java.awt.Font.BOLD, carCountLabel.getFont().getSize()+3));
        carCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        carCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        carCountLabel.setText("     ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(carCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addComponent(carCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mapComponent2Layout = new javax.swing.GroupLayout(mapComponent2);
        mapComponent2.setLayout(mapComponent2Layout);
        mapComponent2Layout.setHorizontalGroup(
            mapComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        mapComponent2Layout.setVerticalGroup(
            mapComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapComponent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapComponent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        oldStartButton.setText("Start");
        oldStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldStartButtonActionPerformed(evt);
            }
        });

        oldPauseButton.setText("Pause");
        oldPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPauseButtonActionPerformed(evt);
            }
        });

        oldStopButton.setText("Stop");
        oldStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldStopButtonActionPerformed(evt);
            }
        });

        increaseSimSpeedButton.setText("+");
        increaseSimSpeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseSimSpeedButtonActionPerformed(evt);
            }
        });

        decreaseSimSpeedButton.setText("-");
        decreaseSimSpeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseSimSpeedButtonActionPerformed(evt);
            }
        });

        simSpeedLabel.setFont(simSpeedLabel.getFont().deriveFont(simSpeedLabel.getFont().getStyle() | java.awt.Font.BOLD, simSpeedLabel.getFont().getSize()+1));
        simSpeedLabel.setForeground(new java.awt.Color(255, 255, 255));
        simSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simSpeedLabel.setText("16x");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oldStartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldStopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decreaseSimSpeedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(increaseSimSpeedButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oldStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oldPauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oldStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(increaseSimSpeedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simSpeedLabel)
                        .addComponent(decreaseSimSpeedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");
        fileMenu.add(jMenuItem1);

        jMenuBar1.add(fileMenu);

        drawingMenu.setText("Drawing");

        drawingEnabledCheckbox.setSelected(true);
        drawingEnabledCheckbox.setText("Enabled");
        drawingEnabledCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawingEnabledCheckboxActionPerformed(evt);
            }
        });
        drawingMenu.add(drawingEnabledCheckbox);

        drawModeButtonGroup.add(drawCarsRadioButton);
        drawCarsRadioButton.setSelected(true);
        drawCarsRadioButton.setText("Cars");
        drawCarsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawCarsRadioButtonActionPerformed(evt);
            }
        });
        drawingMenu.add(drawCarsRadioButton);

        drawModeButtonGroup.add(drawDensityRadioButton);
        drawDensityRadioButton.setText("Density");
        drawDensityRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawDensityRadioButtonActionPerformed(evt);
            }
        });
        drawingMenu.add(drawDensityRadioButton);

        jMenuBar1.add(drawingMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldStartButtonActionPerformed
        //mapComponent2.setSelectedCar(m.addCar());

        m.start();

    }//GEN-LAST:event_oldStartButtonActionPerformed

    private void oldPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPauseButtonActionPerformed
        // TODO add your handling code here:
        m.pause();
    }//GEN-LAST:event_oldPauseButtonActionPerformed

    private void oldStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldStopButtonActionPerformed
        m.stop();
    }//GEN-LAST:event_oldStopButtonActionPerformed

    private void increaseSimSpeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseSimSpeedButtonActionPerformed
        int speed = m.getSpeedMultiplier();

        speed = Math.min(100, speed + (int)Math.sqrt((double)speed));

        simSpeedLabel.setText(speed + "x");
        m.setSpeedMultiplier(speed);
    }//GEN-LAST:event_increaseSimSpeedButtonActionPerformed

    private void decreaseSimSpeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseSimSpeedButtonActionPerformed
        int speed = m.getSpeedMultiplier();

        speed = Math.max(1, speed - (int)Math.sqrt((double)speed));

        simSpeedLabel.setText(speed + "x");
        m.setSpeedMultiplier(speed);
    }//GEN-LAST:event_decreaseSimSpeedButtonActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed

        m.start();
    }//GEN-LAST:event_fileMenuActionPerformed

    private void drawDensityRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawDensityRadioButtonActionPerformed
        mapComponent2.setDrawMode(MapComponent.DRAW_DENSITY);
    }//GEN-LAST:event_drawDensityRadioButtonActionPerformed

    private void drawCarsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawCarsRadioButtonActionPerformed
        mapComponent2.setDrawMode(MapComponent.DRAW_CARS);        // TODO add your handling code here:
    }//GEN-LAST:event_drawCarsRadioButtonActionPerformed

    private void drawingEnabledCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawingEnabledCheckboxActionPerformed
        mapComponent2.setVisible(drawingEnabledCheckbox.isSelected());
    }//GEN-LAST:event_drawingEnabledCheckboxActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
         try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carCountLabel;
    private javax.swing.JButton decreaseSimSpeedButton;
    private javax.swing.JRadioButtonMenuItem drawCarsRadioButton;
    private javax.swing.JRadioButtonMenuItem drawDensityRadioButton;
    private javax.swing.ButtonGroup drawModeButtonGroup;
    private javax.swing.JCheckBoxMenuItem drawingEnabledCheckbox;
    private javax.swing.JMenu drawingMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton increaseSimSpeedButton;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private trafficownage.ui.MapComponent mapComponent1;
    private trafficownage.ui.MapComponent mapComponent2;
    private javax.swing.JButton oldPauseButton;
    private javax.swing.JButton oldStartButton;
    private javax.swing.JButton oldStopButton;
    private javax.swing.JLabel simSpeedLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLabel1;
    // End of variables declaration//GEN-END:variables


    public void benchmarkCarAdded(Car car) {
    }

    public void mapLoaded() {
        mapComponent2.init(m);
    }

    public void nextFrame(double timestep) {

        long seconds = (long)m.getSimulatedTime();
        long minutes = TimeUnit.SECONDS.toMinutes(seconds);
        long hours = TimeUnit.MINUTES.toHours(minutes);

        seconds -= TimeUnit.MINUTES.toSeconds(minutes);
        minutes -= TimeUnit.HOURS.toMinutes(hours);

        String time = "Time: " + String.format("%02d:%02d:%02d", hours, minutes, seconds);

        timeLabel.setText(time);
        carCountLabel.setText(m.getCarCount() + " cars");


        if (drawingEnabledCheckbox.isSelected())
            mapComponent2.update();
    }

    public void logMessage(String message) {
        
    }

}
